## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: ENC(XHooIDVpOVBpogP2TeppRPxSyMSd1izz03J3DKOyYjPgQAywjQ3uSOo8MgsTz/vjYIZTCeEDX3w=)
    username: ENC(kNgmrv5NSZtNZ1jC1L+mr4wN++gdVCKW)
    password: ENC(kNgmrv5NSZtNZ1jC1L+mr4wN++gdVCKW)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true
    properties:
      dialect: Postgres
server:
    port: 8081